### ISSUE TITLE
Could not resolve hostname

### ISSUE THREAD

**Issue by yonacwy** [pete3n/nix-offline-iso#4]
I unplugged internet to test offline the calamares installer did bypass the online check but when installing failed with "Could not resolve hostname" as if its trying to pull online cache and channels.

![PXL_20241218_151308448](https://github.com/user-attachments/assets/aab4e32b-2e9c-4382-99d1-4abc19794f41)

**Comment by pete3n** [comment]
What branch did you build this with?

**Comment by yonacwy** [comment]
The main that has the nixos 24.11

**Comment by pete3n** [comment]
> The main that has the nixos 24.11

It's still broken, and has a giant message that says it is broken. I  am trying to update it, but it appears the behavior has changed from 23.11 to 24.11. It seems that it is now trying to pull from the flake registry: flake-registry.json which is something that I didn't know how to support in the old version (which is why it didn't support flake-based configurations).

**Comment by yonacwy** [comment]
Ok
